# Generated by Django 4.2.10 on 2024-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_title', models.CharField(max_length=100, unique=True)),
                ('chatroom_image', models.ImageField(blank=True, null=True, upload_to='room_images')),
            ],
        ),
    ]
