# Generated by Django 4.2.10 on 2024-03-05 12:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dgljwtt70/image/upload/v1709640781/zazmnydazkuerafegnfk.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
